name: Monitor X Service

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every minute

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'  # Replace '3.x' with your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Replace with actual dependencies if using a requirements.txt file

      - name: Run Python script
        run: python X.py  # Replace 'X.py' with your actual script filename
